ALTER TABLE vpn_nodes
ADD COLUMN IF NOT EXISTS region TEXT;

ALTER TABLE vpn_nodes
ADD COLUMN IF NOT EXISTS backend_weight INTEGER NOT NULL DEFAULT 100;

ALTER TABLE vpn_nodes
ADD COLUMN IF NOT EXISTS last_backfill_at TIMESTAMPTZ;

ALTER TABLE vpn_nodes
ADD COLUMN IF NOT EXISTS last_backfill_error TEXT;
