# Generated by Django 5.1.11 on 2026-03-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='VXcloud - Главная', max_length=120)),
                ('hero_title', models.CharField(default='VXcloud: быстрый прокси (VPN)', max_length=220)),
                ('hero_description', models.TextField(default='VXcloud предоставляет быстрый и легкий прокси (VPN) для стабильного доступа к сайтам, приложениям и мессенджерам.')),
                ('hero_note', models.CharField(blank=True, default='Если вы новый пользователь, начните с инструкций по подключению.', max_length=280)),
                ('primary_button_text', models.CharField(default='Открыть инструкции', max_length=80)),
                ('secondary_button_text', models.CharField(default='Личный кабинет', max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Контент главной страницы',
                'verbose_name_plural': 'Контент главной страницы',
            },
        ),
    ]
