# Generated by Django 5.1.11 on 2026-03-26 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_homepagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.CharField(blank=True, max_length=280)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('show_in_nav', models.BooleanField(default=False)),
                ('nav_title', models.CharField(blank=True, max_length=60)),
                ('nav_order', models.PositiveSmallIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['nav_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True, validators=[django.core.validators.RegexValidator(message='Используйте только a-z, 0-9, точку, дефис и нижнее подчеркивание.', regex='^[a-z0-9._-]+$')])),
                ('value', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Текст сайта',
                'verbose_name_plural': 'Тексты сайта',
                'ordering': ['key'],
            },
        ),
    ]
