from django.db import migrations


def seed_site_texts(apps, schema_editor):
    SiteText = apps.get_model("blog", "SiteText")
    defaults = {
        "admin.branding": "Администрирование VXcloud",
        "admin.site_title": "VXcloud Admin",
        "auth.login.heading": "Вход",
        "auth.login.no_account": "Нет аккаунта?",
        "auth.login.page_title": "Вход - VXcloud",
        "auth.login.signup_action": "Регистрация",
        "auth.login.submit": "Войти",
        "auth.logout.heading": "Выход выполнен",
        "auth.logout.login_again": "Войти снова",
        "auth.logout.page_title": "Выход - VXcloud",
        "auth.signup.has_account": "Уже есть аккаунт?",
        "auth.signup.heading": "Регистрация",
        "auth.signup.login_action": "Войти",
        "auth.signup.page_title": "Регистрация - VXcloud",
        "auth.signup.submit": "Создать аккаунт",
        "base.default_title": "VXcloud Guide",
        "cabinet.config.back_action": "Назад в кабинет",
        "cabinet.config.copy_action": "Скопировать ссылку",
        "cabinet.config.expires_label": "Действует до:",
        "cabinet.config.heading": "Конфиг и QR",
        "cabinet.config.link_label": "Ссылка конфигурации",
        "cabinet.config.page_title": "Конфиг - VXcloud",
        "cabinet.dashboard.expires_label": "Действует до:",
        "cabinet.dashboard.heading": "Личный кабинет",
        "cabinet.dashboard.link_telegram_action": "Привязать Telegram",
        "cabinet.dashboard.logout_action": "Выйти",
        "cabinet.dashboard.open_config": "Открыть конфиг и QR",
        "cabinet.dashboard.page_title": "Кабинет - VXcloud",
        "cabinet.dashboard.renew_action": "Продлить (создать заказ)",
        "cabinet.dashboard.status_active": "Активна",
        "cabinet.dashboard.status_expired": "Истекла",
        "cabinet.dashboard.status_label": "Статус:",
        "cabinet.dashboard.subscription_missing": "Подписка не найдена.",
        "cabinet.dashboard.telegram_link_action": "Привязать",
        "cabinet.dashboard.telegram_linked_label": "Telegram ID:",
        "cabinet.dashboard.telegram_missing": "Telegram не привязан.",
        "cabinet.dashboard.user_label": "Пользователь:",
        "cabinet.link.code_label": "Код привязки:",
        "cabinet.link.current_label": "Сейчас привязан Telegram ID:",
        "cabinet.link.description": "Нажмите кнопку ниже и откройте Telegram-бота. Бот привяжет аккаунт автоматически.",
        "cabinet.link.expires_label": "Код действует до:",
        "cabinet.link.fallback_hint": "Если кнопка не сработала, отправьте боту команду:",
        "cabinet.link.heading": "Привязка Telegram",
        "cabinet.link.open_bot_action": "Открыть бота и привязать",
        "cabinet.link.page_title": "Привязка Telegram - VXcloud",
        "cabinet.link.regen_action": "Сгенерировать новый код",
        "cabinet.open_app.copy_action": "Скопировать ссылку",
        "cabinet.open_app.description": "Сейчас откроем конфиг в приложении автоматически. Если не открылось, нажмите кнопку ниже.",
        "cabinet.open_app.heading": "Открытие в приложении",
        "cabinet.open_app.invalid": "Некорректная ссылка. Вернитесь в бот и нажмите \"Моя подписка\" снова.",
        "cabinet.open_app.open_action": "Открыть конфиг",
        "cabinet.open_app.page_title": "Открытие в приложении - VXcloud",
        "instructions.empty_body": "Добавьте первый пост в админке: /admin.",
        "instructions.empty_title": "Пока нет публикаций",
        "instructions.hero_description": "VXcloud предоставляет быстрый и легкий прокси (VPN) для стабильного доступа к сайтам, приложениям и мессенджерам.",
        "instructions.hero_note": "Ниже - простые инструкции по подключению на iPhone, Android и других устройствах.",
        "instructions.hero_title": "VXcloud: быстрый прокси (VPN)",
        "instructions.page_title": "VXcloud - Инструкции",
        "nav.account": "Личный кабинет",
        "nav.brand": "VXcloud",
        "nav.home": "Главная",
        "nav.instructions": "Инструкции",
        "post.back_to_list": "<- Все статьи",
    }

    for key, value in defaults.items():
        SiteText.objects.get_or_create(key=key, defaults={"value": value})


def unseed_site_texts(apps, schema_editor):
    SiteText = apps.get_model("blog", "SiteText")
    keys = [
        "admin.branding",
        "admin.site_title",
        "auth.login.heading",
        "auth.login.no_account",
        "auth.login.page_title",
        "auth.login.signup_action",
        "auth.login.submit",
        "auth.logout.heading",
        "auth.logout.login_again",
        "auth.logout.page_title",
        "auth.signup.has_account",
        "auth.signup.heading",
        "auth.signup.login_action",
        "auth.signup.page_title",
        "auth.signup.submit",
        "base.default_title",
        "cabinet.config.back_action",
        "cabinet.config.copy_action",
        "cabinet.config.expires_label",
        "cabinet.config.heading",
        "cabinet.config.link_label",
        "cabinet.config.page_title",
        "cabinet.dashboard.expires_label",
        "cabinet.dashboard.heading",
        "cabinet.dashboard.link_telegram_action",
        "cabinet.dashboard.logout_action",
        "cabinet.dashboard.open_config",
        "cabinet.dashboard.page_title",
        "cabinet.dashboard.renew_action",
        "cabinet.dashboard.status_active",
        "cabinet.dashboard.status_expired",
        "cabinet.dashboard.status_label",
        "cabinet.dashboard.subscription_missing",
        "cabinet.dashboard.telegram_link_action",
        "cabinet.dashboard.telegram_linked_label",
        "cabinet.dashboard.telegram_missing",
        "cabinet.dashboard.user_label",
        "cabinet.link.code_label",
        "cabinet.link.current_label",
        "cabinet.link.description",
        "cabinet.link.expires_label",
        "cabinet.link.fallback_hint",
        "cabinet.link.heading",
        "cabinet.link.open_bot_action",
        "cabinet.link.page_title",
        "cabinet.link.regen_action",
        "cabinet.open_app.copy_action",
        "cabinet.open_app.description",
        "cabinet.open_app.heading",
        "cabinet.open_app.invalid",
        "cabinet.open_app.open_action",
        "cabinet.open_app.page_title",
        "instructions.empty_body",
        "instructions.empty_title",
        "instructions.hero_description",
        "instructions.hero_note",
        "instructions.hero_title",
        "instructions.page_title",
        "nav.account",
        "nav.brand",
        "nav.home",
        "nav.instructions",
        "post.back_to_list",
    ]
    SiteText.objects.filter(key__in=keys).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_page_sitetext"),
    ]

    operations = [
        migrations.RunPython(seed_site_texts, reverse_code=unseed_site_texts),
    ]
