# Generated by Django 5.1.11 on 2026-03-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_seed_sitetext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageContent',
        ),
        migrations.AddField(
            model_name='page',
            name='is_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(condition=models.Q(('is_homepage', True)), fields=('is_homepage',), name='unique_homepage_page'),
        ),
    ]
