# Generated by Django 5.1.11 on 2026-04-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_botorder_botsubscription_botuser_paymentevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPNNode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('xui_base_url', models.TextField()),
                ('xui_username', models.TextField()),
                ('xui_password', models.TextField()),
                ('xui_inbound_id', models.IntegerField()),
                ('backend_host', models.TextField()),
                ('backend_port', models.IntegerField()),
                ('backend_weight', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('lb_enabled', models.BooleanField()),
                ('needs_backfill', models.BooleanField()),
                ('backfill_requested_at', models.DateTimeField(blank=True, null=True)),
                ('last_backfill_at', models.DateTimeField(blank=True, null=True)),
                ('last_backfill_error', models.TextField(blank=True, null=True)),
                ('last_health_at', models.DateTimeField(blank=True, null=True)),
                ('last_health_ok', models.BooleanField(blank=True, null=True)),
                ('last_health_error', models.TextField(blank=True, null=True)),
                ('last_reality_public_key', models.TextField(blank=True, null=True)),
                ('last_reality_short_id', models.TextField(blank=True, null=True)),
                ('last_reality_sni', models.TextField(blank=True, null=True)),
                ('last_reality_fingerprint', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'VPN Node',
                'verbose_name_plural': 'VPN Nodes',
                'db_table': 'vpn_nodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VPNNodeClient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_uuid', models.UUIDField()),
                ('client_email', models.TextField()),
                ('xui_sub_id', models.TextField(blank=True, null=True)),
                ('desired_enabled', models.BooleanField()),
                ('desired_expires_at', models.DateTimeField()),
                ('observed_enabled', models.BooleanField(blank=True, null=True)),
                ('observed_expires_at', models.DateTimeField(blank=True, null=True)),
                ('sync_state', models.TextField()),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'VPN Node Client',
                'verbose_name_plural': 'VPN Node Clients',
                'db_table': 'vpn_node_clients',
                'managed': False,
            },
        ),
    ]
